-- Up
CREATE TABLE "user" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"role"	TEXT NOT NULL DEFAULT 'customer' CHECK(role IN ('admin','customer')),
	"email"	TEXT NOT NULL DEFAULT '' UNIQUE,
	"pass"	TEXT NOT NULL DEFAULT '',
	"jwt"	TEXT NOT NULL DEFAULT '',
	"exp"	INTEGER NOT NULL DEFAULT 0,
	"updated_at"	TEXT NOT NULL DEFAULT (datetime('now','localtime'))
);
CREATE UNIQUE INDEX IF NOT EXISTS "UNIQ_email" ON "user" ("email");

CREATE TABLE IF NOT EXISTS "insure" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"title"	TEXT NOT NULL UNIQUE,
	"km"	INTEGER NOT NULL,
	"price"	INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "track" (
	"id"		INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"user_id"	INTEGER NOT NULL,
	"ts"        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"insure_id"	INTEGER NOT NULL DEFAULT 0,
	"distance"	INTEGER NOT NULL DEFAULT 0,
	"lat"		DOUBLE NOT NULL DEFAULT 0,
	"lng"		DOUBLE NOT NULL DEFAULT 0,
	FOREIGN KEY("user_id") REFERENCES "user"("id") ON DELETE CASCADE
);
CREATE INDEX "IDX_userId_ts" ON "track" ( "user_id", "ts" );

CREATE TABLE "gps" (
	"track_id"	INTEGER NOT NULL,
	"ts"		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"lat"		DOUBLE NOT NULL DEFAULT 0,
	"lng"		DOUBLE NOT NULL DEFAULT 0,
	FOREIGN KEY("track_id") REFERENCES "track"("id") ON DELETE CASCADE,
	PRIMARY KEY("track_id","ts")
);

-- Down
DROP TABLE user;
DROP TABLE insure;
DROP TABLE track;
DROP TABLE gps;
